version: '3.8'

services:
  db:
    container_name: matcha_db
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESS_ROOT_PASSWORD: ${POSTGRESS_ROOT_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - matcha_db:/var/lib/postgresql/data

  backend:
    container_name: matcha_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    container_name: matcha_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app
    depends_on:
      - backend

  nginx:
    container_name: matcha_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/app/dist:/var/www/html
    depends_on:
      - frontend

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    container_name: matcha_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  matcha_db: